### ISSUE TITLE
Refresh Current Week Automatically to Determine "Upcoming Games" that have started

### ISSUE THREAD

**Issue by zmottie** [pigskin/kodi-gamepass#119]
When a game starts is it possible to have the addon be aware of system time and start times and refresh itself accordingly? Or possibly grant the ability to launch the game before the start time?

Currently the screen stays on "Upcoming game" even after the game has started.  It would be nice to leave the room and have the TV on the "game will start soon" screen or come back and just press play rather than having to re-select "Week 1".

**Comment by kaileu** [comment]
The Plex Addon for Kodi refreshes the Information on the main Page.
It uses Threads but i am not sure how we can adopt it. But it would be nice to have a more dynamic Addon.
https://github.com/plexinc/plex-for-kodi

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
