### ISSUE TITLE
[usability] can't save a stream to favorites

### ISSUE THREAD

**Issue by ralyodio** [pigskin/kodi-gamepass#208]
The UI looks nice and all....but the default list version is more user friendly. I like to save a game stream to favorites so I can switch back and forth between them easily. I can't do this with current UI on FireTV.

Is there an option to disable the skin?

**Comment by Alexqw** [comment]
There is currently no option to disable the skin. Back when we made the switch to a skinned addon, it was quite difficult as the UI and gamepass logic were tightly coupled. However, now that is much less-so the case.

I personally do not have the time to work on this, but in principal, it should be reasonably straightforward to do.

The other option is to see if we can add a stream to favorites from within the skinned interface. There's a few usability requests for the skin (favorites, resume points, etc).

Anyone have thoughts on this?

---Alex

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
