### ISSUE TITLE
Feature Request: Display Current Score 

### ISSUE THREAD

**Issue by justinro** [pigskin/kodi-gamepass#210]
I would like to display the current score, team possession, field location and down information on the game selection screen. 

I know the Windows 8 Metro App for GamePass has this information, would this be possible to display without spamming the GamePass servers?

**Comment by Alexqw** [comment]
@justinro This can be added, though it certainly should be optional. It would require polling the Game Pass servers at a semi-frequent interval to get the information. #119 is related, and could be completed at the same time.

@justinro Are you interested in working on this?

---Alex

**Comment by justinro** [comment]
Thanks Alex - That's exactly what I was hoping for. I unfortunately don't have any programming skills, but I would be more than happy to debug and test as needed. Let me know if I can help!

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
