### ISSUE TITLE
Start game from beginning, even when it's still live

### ISSUE THREAD

**Issue by dav-sap** [pigskin/kodi-gamepass#278]
Hey developers,
Thanks for the addon it's great. I was wondering if there is a way to start a game from the beginning while it's live, That way i can skip commercials and stuff and be live for the 4th qtr for example. I saw a similar issue talked about for pausing a live feed, and having the feed jump to live when you continue to play it. But didn't understand if that issue from 2 years ago was resolved.

**Comment by aqw** [comment]
@MumfordWiz Yes, this would be a nice feature to have, and it should be doable. Unfortunately, I have no hope for the time right now to dig into poking the GamePass servers to see what we need to tell 'em.

So, sometime "later", unless someone else steps in to take a look at it first. :-)

---Alex

**Comment by bluesbro1982** [comment]
Using the official site today, it looks like even NFL is having issues.  Clicking on "start from beginning" gave me the game live instead.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
