### ISSUE TITLE
Feature request: 2/4 Game Split Screen

### ISSUE THREAD

**Issue by Ghoschdi** [pigskin/kodi-gamepass#328]
The official GP Europe app now supports 4 game split screen.
While i like RedZone, sometimes Split Screen 2 Games is just better. 
I remember there was a similar discussion some time ago, and outcome seemed to be that Kodi does not support this? Has this changed?

**Comment by emilsvennesson** [comment]
PIP is still not supported in Kodi yet (though I've read that it's planned for the future). I agree and think it would be a nice feature but it's not going to happen until it's supported within the Kodi player.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
