### ISSUE TITLE
Game version order

### ISSUE THREAD

**Issue by pyrocumulus** [pigskin/kodi-gamepass#339]
When you get to pick which version of the game you want to see, in the past, the full game would be offered first, followed by other types like the condensed version.

Apparently there has been some rename with the new streaming provider, because the full game is now called 'Game version'. At first I did not understand and thought the whole thing was broken. 'Game version' is not very clear in terms of what it is. That's not really problematic but it is now listed below the condensed version. Is that done on purpose?

If not, I would suggest two things:

- Move the item to the top of the version list (it is most probable)
- Rename the item to 'Full game' (or whatever it was?) or broadcast or something that clearly illustrates that it is the actual full length game broadcast

Curious to know what you guys think.

**Comment by Ghoschdi** [comment]
My preference would be to stick to the same terms and order the official Game Pass apps & services provides if it does not deliver a bad user experience for consistency reasons. That would be:
1. Broadcast - which is the full version
2. Game in 40' - was "condensed" before

**Comment by pyrocumulus** [comment]
Are those the terms that the official apps use? Because those are not the descriptions I get in the add-on at the moment. 'Game version' does not sound like something you'd see on the official website or app. I do have the new NFL Game Pass app at home, will check how it looks in that application :) It's good idea to double check that and use the same names if possible.

**Comment by Ghoschdi** [comment]
Yes (https://user-images.githubusercontent.com/10353742/29879016-34f46ec0-8da4-11e7-8dc4-07770bb63373.png)

**Comment by kaileu** [comment]
But the international version would have different names.

Mit freundlichen Grüßen
Kai Leutner

**Comment by emilsvennesson** [comment]
This was changed after my cleanup (642755defd7439ead508da50579c2abb34e1f450, ea1c684ab2cc1338c3a2674fec762ddeb0f5cabc) and implementation of the get_game_versions() method. Instead of hard coding the game versions, we're now just returning what their API is giving us. I can admit that the 'Game video' name can be a bit confusing.

I don't think it makes a whole lot of sense to change/hardcode this right now because we're going to have to deal with this when we're building the pigskin API for Europe/International Game Pass support.

**Comment by Ghoschdi** [comment]
@emilsvennesson: I just recognized this and your approach makes absolute sense. I just wonder why the API provides different names than they provide via their own apps :)

**Comment by pyrocumulus** [comment]
Keeping the names the same as what the gamepass API is returning is understandable from a developer's standpoint but making them the same as the actual gamepass apps/website is using is a better user experience :)

@emilsvennesson I can understand not changing it right now. Let's remember to improve it when the API layer around pigskin is added then?

**Comment by aqw** [comment]
@pyrocumulus @emilsvennesson Right now, things are in flux, but in the end we should definitely have user-friendly terms for the UI. Whatever the web interface has makes most sense to me (Full Game, Game in 40', etc).

---Alex

**Comment by emilsvennesson** [comment]
@pyrocumulus Definitely!

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
