### ISSUE TITLE
Feature Request: Show broadcasting network

### ISSUE THREAD

**Issue by BaumSchorle** [pigskin/kodi-gamepass#344]
Since this year the pre-game shows of CBS and Fox are broadcasted on GamePass! 
So maybe it would be interesting to add which network broadcasts the game to our games list!

Just an idea, what do you guys think?

**Comment by aqw** [comment]
@BaumSchorle Nice!

I think adding the broadcast partner logos would be nice. The issue is where to put it in the UI. It's getting pretty cramped. ;-)

---Alex

**Comment by jmhotham** [comment]
FYI: the broadcasting network depends on the road team. Fox carries NFC road games and CBS carries AFC road teams. AFAIK NBC has Sunday Night Football, NFL Network / CBS has Thursday Night Football, and ESPN has Monday Night Football.
