### ISSUE TITLE
Crop "news feed" at the bottom to prevent spoiler automatically?

### ISSUE THREAD

**Issue by gun-na** [pigskin/kodi-gamepass#349]
I watch a lot of games during the week - and I guess many other european gamepass users do so, too.

Sadly both CBS and Fox think it is a good idea to show the live scores of parallel games in the "news feed" at the bottom of the screen.

Is it possible to add some kind of "no spoiler mode" and crop that part of the video automatically?

Kodi has a "Vertical shift" option in the video settings menu which gives acceptable results _(values between 1.08 and 1.10)_ in my opinion. The only downside of this solution is, that the picture has a big black bar at the top instead of having a smaller one at the top and at the bottom.

Maybe it is possible to use this feature automatically in this addon? _(of course only if the addon user activates the "no spoiler mode" in the addons settings.)_

**Comment by aqw** [comment]
@gun-na I've long wanted this feature, but I wasn't aware that Kodi had that "vertical shift" option. I always figured we'd need an overlay.

If Kodi exposes this through its API, then this should be relatively easy to implement. Thanks for the suggestion. :-)

---Alex

**Comment by gun-na** [comment]
@aqw Great to hear that I am not the only one looking for this feature 👍 
If you would implement this as a "no spoiler mode" you maybe could "kill" other potential spoilers as well.
For example, the Cardinal - Colts game this week went into overtime and the addon shows "FINAL OVERTIME" instead of "FINAL" under the game. Maybe this could be replaced with "FINAL".

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
