### ISSUE TITLE
Support Kodi 18

### ISSUE THREAD

**Issue by Terminator-95** [pigskin/kodi-gamepass#373]
Hi altogether, since I am also watching Amazon Prime on my Raspberry, which is only possible wit Kodi 19 from the Milhouse builds, it would be really great if you guys could make Gamepass for it available, too. Right now I solved the problem by using two Kodis and rebooting every time I want to watch one or the other. 
Thanks again for all the work you put into this.

**Comment by Displayel** [comment]
Kodi 18 right ?

**Comment by Terminator-95** [comment]
Yes, of course. Sorry for the typo.

**Comment by himynameissteve** [comment]
As far as I can see, you only need to change the version of the xbmc.gui from 5.12.0 to 5.13.0. This has to be done in the addon.xml of the plugin.

I've tried with the latest Kodi 18 build and the plugin worked.
However, the videos didn't start (NFL network live did).
This is problem is also present in the current version of the plugin.

I'll try to find out, what they have changed on their API again.

**Comment by Terminator-95** [comment]
Hi, could you please explain how to change the xbmc.gui (still a newbie to Kodi). Yesterday Gamepass worked fine for me with the WildCard Games.
(all on a Raspberry Pi3)

**Comment by himynameissteve** [comment]
Sure.

First of all on the crash: Maybe may dev environment was corrupt. Had it running on an Ubuntu VM.
Glad it's just me :)

So there are two options for you:

**Option1**
You change the currently installed version of the plugin on-the-fly. This is the easiest method. Keep in mind, that you might have automatic updates enabled and the next time the plugin updates, your changes might get reverted.

You need to find the install folder of the plugin (I don't know by heart where this is on the raspberry and I don't have one at hand at the moment). Google should be able to find this information for you. 
In the root folder of the plugin (not root of kodi), you'll find the addon.xml. This is the same file as you can see here on github. Open it with a text editor and change following line:
`<import addon="xbmc.gui" version="5.12.0"/>`
to
`<import addon="xbmc.gui" version="5.13.0"/>`

Save the file and restart Kodi. The plugin should now load.
Kodi v19 increased the version number of the xbmc.gui, which is a necessary dependency to display visual elements.

**Option2**
If you don't want to change the plugin on-the-fly or can't find it on the raspberry, you can download the plugin as zip from github and do the same change on the addon.xml as described in option 1. After that, re-zip it and re-install the plugin in Kodi (first uninstall, then install). This should do the trick, as well.

Keep in mind, that with both way, it's not guaranteed, that this will still work after the next update of either Kodi or the gamepass addon. Let me know, if you experience problems with one of the described approaches.

**Comment by Displayel** [comment]
i just tried this witht the new Kodi 18 Alpha 2 Release and its not loading the zip file anymore

**Comment by aqw** [comment]
This should be no problem, but first this addon and pigskin needs to become Python3 compatible (aqw/pigskin#3).

**Comment by aqw** [comment]
Also, it seems calls to ``DialogBusy`` need to be replaced:
https://forum.kodi.tv/showthread.php?tid=303073&pid=2739256#pid2739256

**Comment by suikerchiller** [comment]
Recently updated to the latest release candidate of libreelec (now based on Kodi 18). Everything runs smoothly except my favourite plugin :(

I tried manually jumping the version via command line as mentioned above, but the plugin still doesn't work. Any other suggestions???

**Comment by jm-duke** [comment]
@suikerchiller check which version of xbmc.gui is shipped with your Kodi and modify the import accordingly. In my case I had to change the line to 5.14.0.

**Comment by ttobsen** [comment]
> is there anything else you need to do to get the games working again too ? I changed to 5.14 as well on Kodi 18.2 , but only NFL Network is working, not the games

Can confirm, this worked also for me on Kodi 18 (using latest stable LibreELEC Release 9.0.2 on a Raspberry Pi 2).

> 
> EDIT: Never mind, just turn Input Adaptive Streaming off and it works fine

I've enabled Input Adaptive Streaming, and it's working pretty good.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
