### ISSUE TITLE
Relicense Images from MIT

### ISSUE THREAD

**Issue by aqw** [pigskin/kodi-gamepass#391]
While updating our license file, I just realized that technically our images are licensed MIT, which doesn't really translate well to art.

The git log shows that only @BaumSchorle, @eriksoderblom, and I (@aqw) have touched those images.

You guys are the primary creators, so I'm fine with whatever license you prefer. If you're looking for suggestions, then I would recommend either [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) or [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) (basically public domain).

Let me know what license you'd like and I'll make sure its marked accordingly.

Thanks :-)

- [X] aqw
- [ ] BaumSchorle
- [ ] eriksoderblom

---Alex

**Comment by aqw** [comment]
@BaumSchorle @eriksoderblom Ping

Very low priority; just a licensing cleanliness thing.

---Alex

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
