### ISSUE TITLE
Use new Kodi18 getSettingInt()/Bool()/etc instead of getSetting()

### ISSUE THREAD

**Issue by aqw** [pigskin/kodi-gamepass#392]
https://alwinesch.github.io/group__python__xbmcaddon.html

Convenient, for stuff like:

`bitrate_setting = int(addon.getSetting('preferred_bitrate'))`

**Comment by aqw** [comment]
Much of ``resources/lib/kodiutils.py`` can be removed, as it''ll be redundant.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
