### ISSUE TITLE
Not able to see full game nor connect to nfl network live stream

### ISSUE THREAD

**Issue by FirstGuardian** [pigskin/kodi-gamepass#396]
I am not able to watch any full game. Also I am not able to watch ne NFL Network live stream.
If I select a game and choose full game I will then prompted for the screen rate. I take the highest and after that I will returned the the game overview and nothing else happens.

For the NFL Network love stream it is the same. After the selection of the screen rate nothing happens.

I put the log for choosing full game and try not to do other things, so the log should show only that.

I identified some log entried that could show the problem:

16:05:49.388 T:1944   ERROR: ffmpeg[798]: [tls] Unable to read from socket
16:05:49.388 T:1944    INFO: ffmpeg[798]: [hls,applehttp] Opening 'https://vodus-i-video-nfl.akamaized.net/vodus/1e75a2c5-01a5-46d5-97e1-dc754434d411/NoADs_BAL_MIA_720_pre3.ism/QualityLevels(5974673)/Fragments(video=0,format=m3u8-aapl-v3,audiotrack=aac_UND_2_127)' for reading
16:05:49.388 T:1944   ERROR: ffmpeg[798]: [hls,applehttp] Error when loading first segment 'https://vodus-i-video-nfl.akamaized.net/vodus/1e75a2c5-01a5-46d5-97e1-dc754434d411/NoADs_BAL_MIA_720_pre3.ism/QualityLevels(5974673)/Fragments(video=0,format=m3u8-aapl-v3,audiotrack=aac_UND_2_127)'
16:05:49.389 T:1944   ERROR: ffmpeg[798]: [tls] Failed to send close message
16:05:49.389 T:1944   DEBUG: Error, could not open file https://vodus-i-video-nfl.akamaized.net/vodus/1e75a2c5-01a5-46d5-97e1-dc754434d411/NoADs_BAL_MIA_720_pre3.ism/QualityLevels(5974673)/Manifest(video,format=m3u8-aapl-v3,audiotrack=aac_UND_2_127,filter=chromecast)?hdnea=st=1535292248~exp=1535292428~acl=/*~hmac=ed10d67ade9ca75f6b310944ab9231e316deaaa276cc260b7a1e01a546a2d533&hdcore=2.11.3

The problem appears on my PC also on my Raspberry PI 3 Kodi

**Comment by tinzarian** [comment]
It's working fine. You need to enable Inputstream Adaptive.

**Comment by ttobsen** [comment]
Thanks @tinzarian, after changing this setting, NFL Network is working!

**Comment by aqw** [comment]
@FirstGuardian Is this still a problem for you? If so, please pull the latest code and retest.

**Comment by ctcoulter** [comment]
For what it's worth, posted in another issue that is most likely related... I was able to resolve by upgrading to Krypton 17.6 and InputStream Adaptive v2.0.19 (default for 17.6).

**Comment by Ghoschdi** [comment]
I usually have no problems, but today I cannot open the week 1 category and therefore play any live game. But I can play redzone
..big bummer

________________________________
Von: Chris Coulter <notifications@github.com>
Gesendet: Sunday, September 9, 2018 8:40:11 PM
An: aqw/xbmc-gamepass
Cc: Subscribed
Betreff: Re: [aqw/xbmc-gamepass] Not able to see full game nor connect to nfl network live stream (#396)


For what it's worth, posted in another issue that is most likely related... I was able to resolve by upgrading to Krypton 17.6 and InputStream Adaptive v2.0.19 (default for 17.6).

**Comment by ttobsen** [comment]
@Ghoschdi Same here. The week 1 category work approx. half an hour ago, but now I only get errors.

**Comment by Ghoschdi** [comment]
Okay… and newest git version does not login. Says credentials wrong…repo version works

________________________________
Von: Tobias Baumann <notifications@github.com>
Gesendet: Sunday, September 9, 2018 10:54:16 PM
An: aqw/xbmc-gamepass
Cc: Stefan Denz; Mention
Betreff: Re: [aqw/xbmc-gamepass] Not able to see full game nor connect to nfl network live stream (#396)


@Ghoschdi<https://github.com/Ghoschdi> Same here. The week 1 category work approx. half an hour ago, but now I only get errors.

**Comment by ttobsen** [comment]
@Ghoschdi Which version of which repo do you use? Maybe I'll try this version too.

**Comment by Ghoschdi** [comment]
The one from the official kodi repo. Think it is dated august 23rd. Works on red zone at least

________________________________
Von: Tobias Baumann <notifications@github.com>
Gesendet: Sunday, September 9, 2018 10:58:06 PM
An: aqw/xbmc-gamepass
Cc: Stefan Denz; Mention
Betreff: Re: [aqw/xbmc-gamepass] Not able to see full game nor connect to nfl network live stream (#396)


@Ghoschdi<https://github.com/Ghoschdi> Which version of which repo do you use? Maybe I'll try this version too.

**Comment by ttobsen** [comment]
@Ghoschdi Ok, this is the same version that I use. I thought you found a version where full games are working, but seems that I have to stick with the red zone today. :cry:

**Comment by Ghoschdi** [comment]
Works now without any changes on my side


________________________________
Von: Tobias Baumann <notifications@github.com>
Gesendet: Sunday, September 9, 2018 11:02:15 PM
An: aqw/xbmc-gamepass
Cc: Stefan Denz; Mention
Betreff: Re: [aqw/xbmc-gamepass] Not able to see full game nor connect to nfl network live stream (#396)


@Ghoschdi<https://github.com/Ghoschdi> Ok, this is the same version that I use. I thought you found a version where full games are working, but seems that I have to stick with the red zone today. 😢

**Comment by ttobsen** [comment]
Thanks for information, it's working here too! :-)

**Comment by ctcoulter** [comment]
actually started having a problem with week 1 game listing as well, so just ended up watching it on the website. weird, because it was working up until the 2nd set of games came on.

**Comment by ttobsen** [comment]
Same procedure this week. After the early games have finished, it is not possible to load Week 2 games.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
