### ISSUE TITLE
Question: Development Environment

### ISSUE THREAD

**Issue by OnceUponALoop** [pigskin/kodi-gamepass#403]
## General Question - Not an issue

What's your development environment for this look like, what's the debugging workflow, what tools you use, etc...

When looking into pigskin in the past I just wrote a small script to call it while passing traffic through a fiddler proxy to view the output but it's harder when you're trying to debug the actual addon logic.

My initial attempt at a dev environment is just leaving me with a "there's got to be a better way" feeling

###  Setup
- Windows Host
- Setup Ubuntu Kodi VM in Virtual Box
- Host edits Sublime + [SublimeSimpleSync](https://packagecontrol.io/packages/SublimeSimpleSync)
- Kodi edits with vim
- SSH sessions through putty 
- User profile aliases for log file tail, kodi restart, etc...
   ```
   alias LOG='tail -F /home/kodi/.kodi/temp/kodi.log'
   alias LOGE='vi /home/kodi/.kodi/temp/kodi.log'
   alias RESTART='killall -HUP kodi.bin'
   ```
- Start addon via [json-rpc](https://kodi.wiki/view/JSON-RPC_API/v8#Addons-_ExecuteAddon)
   ```
   curl --data-binary '{"jsonrpc": "2.0", "method": "Addons.ExecuteAddon", "params": { "addonid": "plugin.video.nfl.gamepass"}, "id": 1 }' -H 'content-type: application/json;' http://localhost:8080/jsonrpc
   ```

### Workflow
- Make a change in vim or host sublime
- Start addon via rpc
- Monitor log in SSH session
- Rinse and repeat

### References
- [Kodi Python Addon](https://alwinesch.github.io/group__python.html)
- [Kodi Python API Changes](https://alwinesch.github.io/python_revisions.html)

**Comment by aqw** [comment]
> My initial attempt at a dev environment is just leaving me with a "there's got to be a better way" feeling

When working with Kodi, that's definitely the case. I work on Linux, so I don't have the working-remotely setup you have. But what I do is:
* kodi running
* tail -f ~/.kodi/temp/kodi.log
* vim default.py

Whenever I make edits, I exit the addon and re-open it.

That's for Kodi, and I don't know of any better workflow.

However, more and more logic is being moved to pigskin, and I have put a lot of effort recently into making it actually functional standalone --- and adding tests. Unless you're working on integration with Kodi, chances are good you only need pigskin, and for that I recommend that you look at the [aqw/pigskin repo](https://github.com/aqw/pigskin).

For pigskin, my setup is a bit different:
* I setup a python virtualenv with python3 and all my required deps
* ``pytest`` should run cleanly
* I edit my tests and pigskin as needed, and can repeatedly run ``pytest`` without actually contacting Game Pass's servers (vcr.py FTW) --- unless, of course, I've changed what the actual HTTP request is. Then the corresponding "cassette" needs to be updated.
* for sniffing, I just use Chrome's devtools. Everyone kinda has their own favorite tool here (fiddler, wireshark, etc).
* I also have an ``ipython`` instance open. Once I've identified the server and params from devtools, I open a request in ``ipython`` and start playing with the returned data. This gives me a better idea of how I want to actually write the function in ``pigskin.py``.

Once everything is committed to the pigskin project and passing the travis tests, then I cherry-pick the changes into xbmc-gamepass.

I hope that's enough info to give you some insight. Let me know if I can share any more info.

This stuff really should be documented, once I get docs going -- hopefully soonish.
