### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by aqw** [pigskin/kodi-gamepass#404]
Now that pigskin is Python 3 ready, this addon's codebase needs to be updated. Special attention needs to be paid attention to lists and string handling.

Kodi 18 will require Python 3 support (though run using Python 2.7). Kodi 19 will drop Python 2 entirely.

This probably isn't worth undertaking until aqw/pigskin#15 is done.

**Comment by jm-duke** [comment]
Do you need help with the necessary modifications? I'll heavily use this add-on again starting with September, so I'd be more than willing to contribute :)

**Comment by aqw** [comment]
@jm-duke Help is /very/ much appreciated. :-) Though Python 3 compatibility is the easy part. The big effort is with aqw/pigskin. It is 80% complete, but it still needs some work before it is ready for the season. This kodi addon imports pigskin.

If you have the time and the motivation, taking a whack at some of the open issues (or anything else you find) in pigskin would be very well received. :-)

---Alex

**Comment by jm-duke** [comment]
sure, I'll fork right away :)

**Comment by aqw** [comment]
:-D

**Comment by jm-duke** [comment]
Done for Kodi 19
