### ISSUE TITLE
Gamelist does not show up

### ISSUE THREAD

**Issue by Jesia** [pigskin/kodi-gamepass#408]
Hey Guys,

i have an issue with the List of the current Day. It doesnt show up when i select the games and when i click on Week two it says Error.

Week 1 and 3 work fine. 

Its on my Win 10 and on all my RPis

I attached the errorlog

22:30:51.314 T:1496314624 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.jpg
22:30:51.314 T:1496314624 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.png
22:30:51.315 T:1496314624 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.jpg
22:30:51.315 T:1496314624 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.png
22:31:03.296 T:1496314624   ERROR: EXCEPTION: Dialog not created.
22:31:03.374 T:1496314624 WARNING: CSkinInfo: failed to load skin settings
22:31:03.847 T:1925921280 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
22:31:03.847 T:1925921280  NOTICE: LoadJpeg: unable to load /home/osmc/.kodi/addons/plugin.video.nfl.gamepass/resources/skins/Default/media/../../../art/fanart.jpg
22:31:04.013 T:1496314624   ERROR: EXCEPTION: Dialog not created.
22:31:24.786 T:1680864000 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.jpg
22:31:24.787 T:1680864000 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.png
22:31:24.787 T:1680864000 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.jpg
22:31:24.788 T:1680864000 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.png
22:31:27.760 T:1496314624   ERROR: EXCEPTION: Dialog not created.
22:31:27.874 T:1496314624 WARNING: CSkinInfo: failed to load skin settings
22:31:28.297 T:1496314624   ERROR: EXCEPTION: Dialog not created.
22:31:38.043 T:1471148800 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.jpg
22:31:38.044 T:1471148800 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.png
22:31:38.044 T:1471148800 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.jpg
22:31:38.045 T:1471148800 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.png
22:31:58.443 T:1471148800 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.jpg
22:31:58.443 T:1471148800 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.png
22:31:58.443 T:1471148800 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.jpg
22:31:58.444 T:1471148800 WARNING: CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.png
22:31:59.687 T:1496314624   ERROR: EXCEPTION: Dialog not created.
22:32:05.211 T:1925921280   ERROR: CPythonInvoker(6, /home/osmc/.kodi/addons/plugin.video.nfl.gamepass/default.py): script didn't stop in 5 seconds - let's kill it
22:32:10.600 T:1471148800   ERROR: EXCEPTION: Dialog not created.
22:32:18.555 T:1471148800 WARNING: CSkinInfo: failed to load skin settings
22:32:19.002 T:1925921280 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
22:32:19.002 T:1925921280  NOTICE: LoadJpeg: unable to load /home/osmc/.kodi/addons/plugin.video.nfl.gamepass/resources/skins/Default/media/../../../art/fanart.jpg
22:32:19.167 T:1471148800   ERROR: EXCEPTION: Dialog not created.
22:32:24.907 T:1496314624   ERROR: Exception
22:32:24.907 T:1496314624   ERROR: SystemExit
22:32:24.907 T:1496314624   ERROR:  in
22:32:24.907 T:1496314624   ERROR: <bound method _fileobject.__del__ of <socket._fileobject object at 0x5d3b27f0>>
22:32:24.907 T:1496314624   ERROR:  ignored
22:33:49.841 T:1925921280  NOTICE: Samba is idle. Closing the remaining connections

**Comment by Jesia** [comment]
Oh and Redzone and NFL Network works just fine. I tried all versions. in Repo and from Kodi

**Comment by suikerchiller** [comment]
Same here, also dealing with login_failed error when trying to start addon on Kodi

**Comment by Jesia** [comment]
Here once again with debug enbabled

`23:38:13.505 T:4952   DEBUG: CInputManager::ProcessMouse: trying mouse action leftclick
23:38:13.506 T:13732   DEBUG: Thread LanguageInvoker start, auto delete: false
23:38:13.506 T:13732    INFO: initializing python engine.
23:38:13.526 T:13732   DEBUG: CPythonInvoker(4, C:\Users\Konne\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py): start processing
23:38:13.542 T:13732   DEBUG: -->Python Interpreter Initialized<--
23:38:13.542 T:13732   DEBUG: CPythonInvoker(4, C:\Users\Konne\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py): the source file to load is "C:\Users\Konne\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py"
23:38:13.543 T:13732   DEBUG: CPythonInvoker(4, C:\Users\Konne\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py): setting the Python path to C:\Users\Konne\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass;C:\Users\Konne\AppData\Roaming\Kodi\addons\script.module.certifi\lib;C:\Users\Konne\AppData\Roaming\Kodi\addons\script.module.chardet\lib;C:\Users\Konne\AppData\Roaming\Kodi\addons\script.module.idna\lib;C:\Users\Konne\AppData\Roaming\Kodi\addons\script.module.iso8601\lib;C:\Users\Konne\AppData\Roaming\Kodi\addons\script.module.m3u8\lib;C:\Users\Konne\AppData\Roaming\Kodi\addons\script.module.requests\lib;C:\Users\Konne\AppData\Roaming\Kodi\addons\script.module.urllib3\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
23:38:13.543 T:13732   DEBUG: CPythonInvoker(4, C:\Users\Konne\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py): entering source directory C:\Users\Konne\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass
23:38:13.543 T:13732   DEBUG: CPythonInvoker(4, C:\Users\Konne\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py): instantiating addon using automatically obtained id of "plugin.video.nfl.gamepass" dependent on version 2.25.0 of the xbmc.python api
23:38:13.905 T:13732   ERROR: EXCEPTION: Dialog not created.`

**Comment by Ghoschdi** [comment]
Same problem today. Late games start, cannot open the week 3 list...

**Comment by kaileu** [comment]
Could you post a debug log maybe no inside Github?
Guthub doesn‘t show the full log sometines on mobile devices

**Comment by kneespan** [comment]
Same here since week 5 on libreelec (raspberry). Fresh start in the morning - no hanging log in on other device or such. Game list for the current week doesn't show up. When i click the week I get an error.
Where do I find the relevant debug log info to paste here? Thank you.

**Comment by kneespan** [comment]
How about some feedback here? Do you need more information? Thank you.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
