### ISSUE TITLE
60fps support

### ISSUE THREAD

**Issue by Manuel86001** [pigskin/kodi-gamepass#411]
Sorry to place my question here- but this question might be relevant to more people. Is 60fps supported for Gamepass (EU-Version) via Kodi?

**Comment by kaileu** [comment]
As far as i noticed there is no 60fps via Gamepass Europe App so the answer is no.
We only support the resolutions from the Gamepass App/Web.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Ghoschdi** [comment]
Wasn't the 60fps version limited to the XBOX subscribers ?

**Comment by yiwesi** [comment]
> 
> 
> Wasn't the 60fps version limited to the XBOX subscribers ?

 1980x1080px at 6Mbps only for Chromecast and AppleTV

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
