### ISSUE TITLE
future of xbmc-gamepass and pigskin

### ISSUE THREAD

**Issue by aqw** [pigskin/kodi-gamepass#429]
Following up on a conversation in #428, we should figure out a way to reduce the friction for contributors despite my lack of involvement.

I see a few options:
1) This continues to be the canonical location for both projects. @jm-duke (and any others willing to contribute) is given commit privileges.
2) I archive both projects, and add notes pointing to @jm-duke's forks.
3) Create a new GitHub organization and move these projects there (perhaps `pigskin/kodi-gamepass` and `pigskin/pigskin`). GitHub's will automatically redirect people. Give me and @jm-duke (and others who are interested) commit access.

Thoughts?

**Comment by jm-duke** [comment]
Well, I'd opt for 3. Both repos are now in your personal namespace, which you'll maybe want to use for something different in the future. Just look at mine, it's a mess. So I wouldn't want anything pointing there either ;-)

pigskin as org sounds good, repo names as well.

**Comment by aqw** [comment]
Sounds great. :-)

It looks like the "pigskin" namespace is currently in use by a dormant account. I have contacted GitHub to see if they'd be willing to open up that name for us. Otherwise, we'll come up with something else.

**Comment by jm-duke** [comment]
Bugger :)

Well, we could opt for football-bromance, to honor Coach Esume and Bjoern Werner :kiss: :eyes:

**Comment by aqw** [comment]
There's still hope that they'll give us the namespace. They do that sometimes when obviously dormant accounts are blocking active users.

It seems they aren't answering support requests on the weekend (which is sane). I expect they'll respond by Tuesday or Wednesday. Then we'll see what adventure we choose. :-)

**Comment by aqw** [comment]
Wonderful. GitHub was kind enough to classify the old account as name squatting, and freed up the name. We now have a "pigskin" organization. :-)

@jm-duke I have sent you an invite. Once you accept, I'll give you all the happy rights, and we'll go from there. :-)

**Comment by jm-duke** [comment]
Awesome :tada:

**Comment by aqw** [comment]
I have granted you organizational superpowers. ;-)

All the work seems to be done, and you can now push, create repos, etc.

Enjoy, and thanks for working on the addon!
