### ISSUE TITLE
Not working Kodi 19

### ISSUE THREAD

**Issue by crak3rjack** [pigskin/kodi-gamepass#432]
@jm-duke I have a account is working fine in the web page... but not working in kodi 19.
https://pastebin.com/1458fMyj

**Comment by ohhmyy** [comment]
Hi. As far as i can tell, you're not using the latest version. Current version is v2021.03.14.
In your pastebin it says v2021.03.02.

**Comment by crak3rjack** [comment]
@ohhmyy where can i get the latest version or repo for Kodi 19 and thanks

**Comment by ohhmyy** [comment]
Just download the zip [https://github.com/pigskin/kodi-gamepass/archive/refs/heads/matrix.zip](https://github.com/pigskin/kodi-gamepass/archive/refs/heads/matrix.zip)

**Comment by jm-duke** [comment]
No update in 10 days, guess ohhmyy got it right, thanks :)
