### ISSUE TITLE
No 1080HD quality streaming

### ISSUE THREAD

**Issue by blueveno** [pigskin/kodi-gamepass#434]
I got m3u8 links from read url :https://live-i-backup-nflvideo.akamaized.net/ch22/3495a8b0-6121-4f3d-96e1-343c3c6a9eb0/6f3a93cc-8a3f-4ac3-8dff-5297559ec351.ism/manifest(format=m3u8-aapl-v3,filter=hls)?hdnea=st=1629190842~exp=1629191022~acl=/ch22/3495a8b0-6121-4f3d-96e1-343c3c6a9eb0/*~data=a55e8e63-49a5-4abb-b493-a4568ed30734~hmac=b749578b28ca72f58e3424abb1f5467d73544e82d0104be1633827caf993c154&hdcore=2.11.3"

[https://i.imgur.com/zFPDVHh.png](url)
And got stream with bitrate. I use 1600x900 - 4968 stream with FFMPEG to live streaming Youtube. But just only 720HD no 1080 quality. While resolutions are cleaner, bitrates are more informative about the quality of the stream. 
Thank you so much!

**Comment by jm-duke** [comment]
Sorry, but I don't really get your point. Please be more descriptive and add details.

**Comment by jm-duke** [comment]
No update, closing this request.
