### ISSUE TITLE
Settings dialog cannot be opened from inside the app

### ISSUE THREAD

**Issue by jm-duke** [pigskin/kodi-gamepass#438]
[...]

However i couldn't open the settings from the icon inside the app.. had to do it from the outside.

_Originally posted by @kabukimurder in https://github.com/pigskin/kodi-gamepass/issues/428#issuecomment-801986550_

**Comment by jm-duke** [comment]
Need to update my testberry and test this with a more recent version of Kodi 19

**Comment by TopRamenDom** [comment]
We need to have our own credentials to use the add on correct ?

**Comment by jm-duke** [comment]
> We need to have our own credentials to use the add on correct ?

Yup

**Comment by jm-duke** [comment]
omg, good catch. I obviously forgot to update the skins when renaming stuff :D 

Thanks!
