### ISSUE TITLE
addon is not in the kodi repository

### ISSUE THREAD

**Issue by shangri26199** [pigskin/kodi-gamepass#439]
as the title says, the addon is not listed in the kodi repository as of today. 

I do think it is still installable via .zip packages. but this is not "the recommended way"

**Comment by jm-duke** [comment]
Yeah, I know. Getting an add-on into the official repository is a kinda lengthy process ;-)

I currently lack time to initiate this process, but it is on my todo list. Thanks for raising
this issue, now it's tracked in here as well.

Cheers.

**Comment by piejanssens** [comment]
Can we help in any way?

We have some great CI setup in this shared community organisation of well maintained Kodi video add-ons to make releases to the Kodi repo a breeze. https://github.com/add-ons

**Comment by BrainKingSoldier** [comment]
> 
> 
> as the title says, the addon is not listed in the kodi repository as of today.
> 
> I do think it is still installable via .zip packages. but this is not "the recommended way"

Where do I get a ZIP package nowadays? I'm just a simple non-programmer gamepass subscriber :D

**Comment by piejanssens** [comment]
https://github.com/pigskin/kodi-gamepass/archive/refs/heads/master.zip

**Comment by jm-duke** [comment]
> Can we help in any way?
> 
> We have some great CI setup in this shared community organisation of well maintained Kodi video add-ons to make releases to the Kodi repo a breeze. https://github.com/add-ons
Oops, I totally missed that one...

I wouldn't call this add-on well maintained, but I'll absolutely check out your project, thanks!

**Comment by BrainKingSoldier** [comment]
thanks buddy

**Comment by piejanssens** [comment]
@jm-duke Even without migrating to the other organisation, can I offer some help to maintain this add-on and get a new version in the Kodi repo?

**Comment by jm-duke** [comment]
I'll tackle this one after this season, life should be quieter in Q2.

Cheers.

**Comment by jm-duke** [comment]
https://github.com/xbmc/repo-scripts/pull/2306 created. 

@aqw : Can you please add a comment to the PR giving me the permission to submit the gamepass addon?

They asked for it before:

> It seems you are not the dev that submitted the most recent version (https://github.com/xbmc/repo-plugins/commit/45f49b15205ccfc052871e28c84d45919b6d30aa). So you will need to ask permisson from him/her before we will accept this PR.

**Comment by aqw** [comment]
Thanks for the ping. I have commented in the upstream PR.

If anything else comes up, let me know. :-)

Good luck with the season!

**Comment by jm-duke** [comment]
Awesome, thank you :)

**Comment by Brandon1212b** [comment]
> https://github.com/pigskin/kodi-gamepass/archive/refs/heads/master.zip

Is this link still the best way to download? Is there a repo for this?

**Comment by jm-duke** [comment]
Yes, it still is. I submitted a request to add it to the official repository, but this request is still pending.

**Comment by Brandon1212b** [comment]
Awesome, thank you for the update

**Comment by jm-duke** [comment]
If you install from the master branch, please ensure that the inputstream.adaptive addon is also installed and enabled in Kodi. And please enable "Use inputstream adaptive" in the Kodi Gamepass addon settings, fixed bitrate playback is no longer supported, see #437 for details

**Comment by jm-duke** [comment]
No, https://github.com/pigskin/pigskin is a big rewrite, which most probably won't work at all. I'm not sure, if this rewrite will ever be finished tbh ;-)

NFL Network usually takes quite a while to load, how long did you wait?
Can you enable debug logging, access NFL Network again and upload the log?

**Comment by Brandon1212b** [comment]
That was it. I was just being too impatient. I tried again and it showed up after 30 seconds. Thanks again @jm-duke for being so helpful.

**Comment by jm-duke** [comment]
Great, thanks for the feedback!

@Brandon1212b out of curiosity, would you mind sharing where you're located? I just would like to know, where this add-on can be used nowadays.

**Comment by jm-duke** [comment]
PR was merged by the Kodi team, the add-on is officially back ;-)
