### ISSUE TITLE
menu of current weeks games

### ISSUE THREAD

**Issue by JimmyJones79** [pigskin/kodi-gamepass#440]
When you open the current weeks games from the left side navigation bar I get "unexpected error='(. Please enable debugging in Kodi and submit a bug report"

Now this happened last week, week 1 and now is happening on week 2.
 
Today week 1 games are all there and play fine. Also last Sunday (week 1) RedZone and NFL network worked fine.  Week 3 games all display as well but since they haven't happened obviously you can not watch them. This error only seems to happen on game day with the current weeks menu when selected displays that error code.

Any insight is appreciated

**Comment by ohhmyy** [comment]
Hi, I think this is the same error I had. Should be fixed in one of the last versions. 
See here: https://github.com/pigskin/kodi-gamepass/issues/433
So either download the latest version from here or fix it yourself in default.py.

**Comment by JimmyJones79** [comment]
> Hi, I think this is the same error I had. Should be fixed in one of the last versions.
> See here: #433
> So either download the latest version from here or fix it yourself in default.py.

Ok I'll check it out, thank you

**Comment by JimmyJones79** [comment]
> > Hi, I think this is the same error I had. Should be fixed in one of the last versions.
> > See here: #433
> > So either download the latest version from here or fix it yourself in default.py.
> 
> Ok I'll check it out, thank you

Ok just did the edit, now it's working lovely. Thank you for the help.
For anyone wondering how to do this, this is what I did.
1. Unzipped the Add-on
2. Located default.py
3. Opened up default.py in notepad++
4. Went down to line 336 and replaced existing line with game_info += ("[CR]» Live «").encode('utf-8')
5. Saved the file
6. Recreated a zip file with the new default.py file
7. Open Kodi
8. Uninstalled the Gamepass addon (keep the existing add-on data)
9. Installed the new Gamepass addon from the zip file I created 
10. Launch the add-on
11. Cheered because it worked

**Comment by jm-duke** [comment]
> For anyone wondering how to do this, this is what I did.
Or you could have downloaded the master branch, this bug is already fixed there ;-)
