### ISSUE TITLE
Suggestion: Change logo URL

### ISSUE THREAD

**Issue by ohhmyy** [pigskin/kodi-gamepass#441]
Hi @jm-duke. First of all thank you for keeping the addon running. Have you thought about changing the logo URL to show the current team logos?
I did that locally (changed to https://static.www.nfl.com/t_thumb_squared/f_auto/league/api/clubs/logos/%s, then also had to adjust the image dimensions and position in the xml in the skin):
![pass](https://user-images.githubusercontent.com/88911468/184992126-77878f6b-f264-4106-b472-6a6b21e96929.png)

**Comment by jm-duke** [comment]
Sure, why not. the logos you use look nice indeed :)

Would you consider creating a pull request for the necessary changes?

Cheers,
Duke.

**Comment by ohhmyy** [comment]
#442 
Done
