### ISSUE TITLE
Feature Request: Implement widget compatibility

### ISSUE THREAD

**Issue by Brandon1212b** [pigskin/kodi-gamepass#445]
I am new to GitHub so if this post doesn’t belong here please let me know where I can post it:

Feature Request: Implement widget compatibility

Would it be possible to have the ability to see a today’s game section where you can watch todays live game? Having it set up so this can be added as a widget for the home screen to work with skins such as Arctic Horizon 2.

Similar is done for the MLB.TV add on https://forum.kodi.tv/showthread.php?tid=262745. I’m including a picture of what the MLB TV add on looks like on the Home Screen.

Is this possible or would this be out of the scope of the project?
![image](https://user-images.githubusercontent.com/111893060/189164617-a5e3e336-4c91-41b6-8067-24e0cdc1ebb1.jpg)

**Comment by jm-duke** [comment]
I'd need to look into this in more detail, to see how MLB.TV is doing it and if we can apply the same approach to this add-on.

Don't expect anything to happen anytime soon, but I will take a look :)

**Comment by jm-duke** [comment]
Closing this issue, since NFL has canceled the Gamepass service
