### ISSUE TITLE
Streams keep aborting

### ISSUE THREAD

**Issue by AleXSR700** [pigskin/kodi-gamepass#446]
Hello everyone,
maybe this is a problem on my end or a problem with the game stream, but I have tried multiple times to watch the full game replay if Bills vs Rams an it always aborts at some point. 
First after a few minutes, then at a later point. 

Is anybody else experiencing this issue or just me?

**Comment by bender711** [comment]
Same here. At about minute 30 (30:58) and about minute 50 (51:04) the stream starts to stutter and then aborts. The times are always the same.

But it seams to be a problem with the GamePass stream itself. Because when watching with the official app on a Fire TV the streams stop at the very same spots and the app shows an message saying "OOPS! Something went wrong".

**Comment by Taijian** [comment]
I have the same issue with the stream on this addon (running on CoreElec on an Odroid N2). At certain points in the stream, playback stops and then crashes reliably.

However, playback on my laptop via the gamepass website does work.

**Comment by ohhmyy** [comment]
Hi. It really seems to be a problem with the game stream. I'm having issues too with both the Kodi addon and the official app for Fire TV at the same times in the stream (website is fine though).
People are also complaining on Twitter https://twitter.com/danielbryantuk/status/1568286773071036422

**Comment by jm-duke** [comment]
If the stream aborts during the game, it's most likely an issue with the stream itself or Kodi. The add-on is not involved in the streaming itself, we just pass the URI to Kodi, and Kodi takes care of playback.

Thanks to all who helped analyzing!

Closing this issue.

**Comment by AleXSR700** [comment]
Is there any way of then adding an option to switch to html stream? It seems to be working via browser. 
Kind of a fallback option.

**Comment by jm-duke** [comment]
I don't see it at this time, no.

But if you feel like it, please go ahead and reverse-engineer the browser version of Gamepass. If you can find a new method of resolving the stream URIs, which works for the games and NFL Network content, I'd be happy to accept a pull request.

**Comment by AleXSR700** [comment]
I would love to but I am a buffoon ^^
