### ISSUE TITLE
Start from beginning instead of Live?

### ISSUE THREAD

**Issue by AleXSR700** [pigskin/kodi-gamepass#447]
Hello everyone,
maybe I am misremembering, but didn't it used to be possible to start games from the beginning like in the App?

Now, when a game is live the nfl app asks me if I want to go live or start from beginning. But the kodi addon does not and always goes live.

Would be great if this option returned or became available :)

Thank you
Alex

**Comment by jm-duke** [comment]
Yeah, I know the app can do that, and Gamepass in the browser too. I don't think this add-on ever had this feature though.

I did go through the debug log in detail yesterday to check another issue, and I did not see any possibility to request a live stream from the beginning. Maybe I missed it, so I'll check once more.

**Comment by AleXSR700** [comment]
Maybe it is a feature they put in their apps (unlike hide scores on Android TV^^).

If it is not implemented, maybe it could be added as an add-on feature that if game is "Live" create a pop-up with "Go Live" where it does what it does now and another option to "Start from beginning" where it jumps to 0000 (similar to when a keyboard is connected and you enter the time to jump to)?

**Comment by jm-duke** [comment]
Yeah, it's not as easy as it sounds. There is no time index in the stream URLs, at least I haven't identified any yet. So there's no way currently to find out what index 0 refers to.

**Comment by AleXSR700** [comment]
What a shame. They never make it easy for people:(

But I very much appreciate you looking into and  considering it! :)

**Comment by ohhmyy** [comment]
Hi. Could this inputstream.adaptive property be used for this purpose?
[inputstream.adaptive.play_timeshift_buffer](https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptiveplay_timeshift_buffer)

**Comment by jm-duke** [comment]
Thanks for the hints, I'll take a closer look as soon as I can. Just a bit busy right now...

**Comment by jm-duke** [comment]
> Hi. Could this inputstream.adaptive property be used for this purpose? [inputstream.adaptive.play_timeshift_buffer](https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptiveplay_timeshift_buffer)

I tested the play_timeshift_buffer property, but it has no effect :(

> edit: Or maybe use a workaround like in the NHL addon: [xbmc/inputstream.adaptive#94 (comment)](https://github.com/xbmc/inputstream.adaptive/issues/94#issuecomment-519909189)

I looked into this a bit as well, but I don't think we can use the same approach for NFL Gamepass. If I understood it correctly, he starts streaming the actual content, before the user is selecting it. Can't do that with the NFL content, there's just too many :)

I'm afraid I need to reverse engineer the API the browser and/or the app are using to decipher, what they send to get a stream, which starts from the beginning. Let's see, if Postman can help with that.

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
