### ISSUE TITLE
Sending out SoS

### ISSUE THREAD

**Issue by Coolbreezy81** [pigskin/kodi-gamepass#449]
Can someone make a video how to make this work. I'm a newbie and can not figure this out. Trying to get this working for the boys to catch some games when we can. Downrange right now and looking for some help if possible.

**Comment by jm-duke** [comment]
Hey,

it actually should be fairly easy to set up:

1. Install the add-on in your Kodi from the official repositories
2. Configure the add-on (at least username and password)
3. Watch games

Where are you stuck exactly?

Cheers.

**Comment by Coolbreezy81** [comment]
Configure the add-on (at least username and password) How do I do this? I don't have a paid version I thought this was a free cracked version...

**Comment by Coolbreezy81** [comment]
I thought this was a free version that I saw this work before from another guy who showed me and that's how it brought me to here. Do you know where I can get free version

**Comment by jm-duke** [comment]
Well, it is free in a sense. You can install and use the add-on in Kodi for free. But you still need a valid NFL Gamepass subscription to view games and other content.

And sorry, I don't know of any means to view Gamepass content without subscription.

Gonna close this issue now, as this discussion is clearly off topic :)
