### ISSUE TITLE
Plugin stopped working ( TypeError: string indices must be integers)

### ISSUE THREAD

**Issue by AleXSR700** [pigskin/kodi-gamepass#450]
Hello,

is the plugin working for anybody at the moment?

I am getting error messages.
Login etc. is correct. I can stream from the Android NFL app.

https://controlc.com/7c92d092

Thank you
Alex

**Comment by jm-duke** [comment]
Yeah, same here.

Something's changed in the API, no idea yet what and why. The add-on fails to retrieve stream content URLs for the chromecast stream type used so far, hls is still working though...

**Comment by jm-duke** [comment]
Please try https://github.com/pigskin/kodi-gamepass/commit/6e25910659c15710117997c6bd119ec5712817e1 and see, if that works for you

**Comment by ohhmyy** [comment]
The workaround works for me. The stream now starts again. Thank you very much for this.
However, the highest resolution is now 1600x900. Wasn't it 1920x1080 before?
![grafik](https://user-images.githubusercontent.com/88911468/198684826-c040260f-b801-4f4f-9e2b-df55b9e75a3e.png)

**Comment by AleXSR700** [comment]
https://support.nflgamepass.com/hc/en-gb/articles/360005287033-Can-I-adjust-the-video-quality-#:~:text=Up%20to%201280x720px%20at%204.5,only%20for%20Chromecast%20and%20AppleTV

Depends on the stream, afaik.

**Comment by jm-duke** [comment]
The workaround seems to be working fine, but what bugs me is that two out of three streaming contents fail. If NFL Gamepass decides to change the API for the single remaining stream, we're fucked. I hope I can find some time in the near future to reverse engineer the changes required to the content retrieval logic.

**Comment by jm-duke** [comment]
Well, had to do a bit too much Python coding in the last months, so I kinda was fed up with scripting and didn't have time or the will to look into this in more detail.

Gonna close this bug for now and will maybe pick it up at a later date.
