### ISSUE TITLE
Getting error in the addon

### ISSUE THREAD

**Issue by crak3rjack** [pigskin/kodi-gamepass#451]
Hi my account works fine in the Android app and website "see photo" but im getting error from the addon, here's the log hope i can get help and thanks
https://pastebin.com/MTjK2gCW
![Capture](https://user-images.githubusercontent.com/59179646/198676285-b42a1df5-1748-4ddb-bfe0-a71e0d35e715.jpg)

**Comment by jm-duke** [comment]
Hi,

the log seems to be cropped, there's only 244 lines and I cannot see any issue in these lines.

When do you get the error?
As soon as you try to stream content? If yes, this might be a dup of #450

**Comment by crak3rjack** [comment]
@jm-duke Yes when I try to open a stream

**Comment by jm-duke** [comment]
Ok, then please take a look at the workaround I proposed in #450. Works for me.

**Comment by jm-duke** [comment]
Live works, my wife and I verified a few time already ;-) Closing this one now.
