### ISSUE TITLE
Feature request: Show date (or weekday) of game

### ISSUE THREAD

**Issue by AleXSR700** [pigskin/kodi-gamepass#452]
Hello,
I am not even sure if this information is available but if it is: would it be possible to show either the date or weekday of the games?

Background:
sometimes one does not know which game is the Thursday night game(s) oder Sunday/Monday or the Saturday games. Since they are not part of Redzone, it can happen that Redzone will spoiler them right at the beginning because you thought the game(s) were on Sunday ^^

**Comment by jm-duke** [comment]
Show the date and/or weekday where exactly? In Gamepass' game day lists? Or in NFL Network stuff, since you mentioned Redzone?

**Comment by AleXSR700** [comment]
In Gamepass's gane day list.
Each week has a list of games and right now it is impossible to tell which was the Monday Night game or the Thursday or which was early window or late window.
So ideally, each game would show date and time of kick off.

**Comment by jm-duke** [comment]
Hm, that's not there? :)
Man, season is over and I totally have no idea anymore, what the add-on looks like :rofl: 

I'll check and play with adding some additional info. Need to look, if this fucks up the UI though.

**Comment by AleXSR700** [comment]
If you have access to the data, the UI should be just fine.
More than enough space underneath the "Final".

EDIT: sorry, github isn't allowing me to upload images from my mobile. I will post one if I can.

**Comment by AleXSR700** [comment]
I seem to be too inexperienced to get it to work once I want to join a string plus the variable, but I tried without the string and it works.

I am sure it is something really basic that I am missing -.-
`game_info = game['phase'] + '(' + datetime_obj.strftime(datetime_format) +')'`
because this works
`game_info = datetime_obj.strftime(datetime_format)`

Optionally with a new line.

https://github.com/pigskin/kodi-gamepass/compare/master...AleXSR700:kodi-gamepass_datetime:master

(Obviously I cannot create a pull request while my code is not working with the `game_info` above

**Comment by AleXSR700** [comment]
It took me a few tries but I think I now got it working properly.

https://github.com/pigskin/kodi-gamepass/pull/454

I did not add translations (only English at the moment). I/you can of course add if necessary.

**Comment by jm-duke** [comment]
PR #454 merged
