### ISSUE TITLE
Feature request: make "jump to current game day" optional

### ISSUE THREAD

**Issue by AleXSR700** [pigskin/kodi-gamepass#453]
Hi everyone,
at the moment, when you select "Games", the plugin directly  jumpa to the latest game day.
This means that if you want to watch the previous games (e.g. you missed a divisional) you will automatically see the next/upcoming games. This will spoiler the game you missed.

Any chance of making this optional? Maybe just start at the top of the list as it does for the nfl network?

Thank you
Alex

**Comment by jm-duke** [comment]
Yeah, I can see that this might be useful and it shouldn't be too hard to implement. Gonna take a look at it.

**Comment by jm-duke** [comment]
Code is updated in branch [453-feature-request-make-jump-to-current-game-day-optional](https://github.com/pigskin/kodi-gamepass/tree/453-feature-request-make-jump-to-current-game-day-optional).

Looks fine on my side. Can you run the branch on your Kodi and check, if the change addresses your feature request?

**Comment by jm-duke** [comment]
Thanks for the feedback, code is merged to master
