### ISSUE TITLE
Bye bye Gamepass

### ISSUE THREAD

**Issue by jm-duke** [pigskin/kodi-gamepass#455]
Well, all Gamepass users got the notification today that the service is canceled by the NFL and DAZN is taking over.

Let's see where this story goes, but this most likely is also the end of this Kodi add-on. There is a DAZN add-on, gonna do some testing in the coming days to check the NFL support.

**Comment by AleXSR700** [comment]
I was just about to post the same thing.

After another ridiculous NFL Germany Ticketmaster experience, this was the second terrible news of the day -.-

**Comment by jm-duke** [comment]
Yeah, really sucks. I always wanted to stay clear of DAZN, especially with their ridiculous DRM crap...

**Comment by snowstormfred** [comment]
Which DAZN add-on is that? Maven85's?

**Comment by jm-duke** [comment]
Yes, tried Maven85's now, but failed. I can login and browse the DAZN content, but I cannot play any streams. Kodi logs a 403 error, when it tries to communicate with the license server.

Gonna do some more testing on the weekend I suppose.

And btw:
Watch out, if you register for DAZN following the instructions provided in the info mail. I took a wrong turn or DAZN just fucked me over, because I had to subscribe to a DAZN plan before I was able to subscribe to NFL Gamepass. Luckily, i took the flexible option, so I was able to cancel the plan immediately again. Still, cost me € 30 :(

**Comment by jbarry786** [comment]
Absolutely brutal news.

Over the last few years we had DRM free streams which enabled me to simply capture the streams live or later and play the games as I pleased. Oh, I also was able to apply some crop filter to hide the scores at the bottom and stay free of spoilers from other games I may watch still.  That was so enjoyable and such a huge benefit of the streams not being protected.

Then we also had the add on to easily allow us to stream games.

Now all of that will be gone... and this is going to be really really messy to watch the games and watch as many games as I did: just think about the game length and info... if you watch on demand, you will almost figure out if the game goes to OT. I wont be able to capture the games and watch offline.

RIP

I probably will end up just finding a way to get games downloaded and watch from there. Really doubt streaming games will be fun --- and we shall see if they even cut the ads!

**Comment by AleXSR700** [comment]
Although I share your sentiment, I think you did not use the GP properly before.
You could already re-watch the games. Even better than recording them because the re-lives on GP were ad-free.
And you were already able to download games and watch them offline with the GP app.
If we are lucky, both will remain available. Although right now the re-lives are no longer ad-free.

So not much changed for you except cropping. And you could crop KODI instead of the addon.

**Comment by jbarry786** [comment]
> the re-lives are no longer ad-free.
> 
> So not much changed for you except cropping. And yo

On Sundays, sometimes using Streamlink, I'd capture 3 games live and watch them "at the same time" or capture a game and watch a bit later... so I could easily skip the ads. I even had short cuts set up to jump ahead 3 mins and skip the commercials.

Then I'd stream the best 4PM game off the add on if I was still awake.

Of course, next day, we know the ads were cut, so I 'downloaded' those games. Honestly, I had the gamepass purely to capture the streams to my computer and then watch the games as I wanted to.

Now... I cant see how I am going to avoid the spoilers from that annoying bottom bar... let alone be able to go back and forward as quickly as we do if we have the game on file.

I bet that if we pause a game on Dazn, it brings up a menu with the length of the game too. 

In any case, it was always surprising that the DRM free streams lasted as long as they did... I guess the day arrived the fun was over.

**Comment by jm-duke** [comment]
> Yes, tried Maven85's now, but failed. I can login and browse the DAZN content, but I cannot play any streams. Kodi logs a 403 error, when it tries to communicate with the license server.
> 
> Gonna do some more testing on the weekend I suppose.
> 
Updated my setup to Nexus today and now the DAZN addon is working fine. I streamed some test content from last season, looks good. So I should be set for the upcoming games  :)

**Comment by jbarry786** [comment]
How do you crop the bottom bar with Kodi?

**Comment by AleXSR700** [comment]
Maybe the wrong place for this discussion, but I think there used to be a setting under system - display.
But that is like the general screen size adjustment like fire tvs have. No sure if you get full control of everything.

I personally use the "just don't look at scroll bars" approach :-D

**Comment by jbarry786** [comment]
> Maybe the wrong place for this discussion, but I think there used to be a setting under system - display. But that is like the general screen size adjustment like fire tvs have. No sure if you get full control of everything.
> 
> I personally use the "just don't look at scroll bars" approach :-D



I covered the tv with a paper. :)

I will have to research again, but last season I was not able to find a setting in kodi to crop or simply move the video "down". It should be possible, but I just wasnt able to figure it out.

**Comment by AleXSR700** [comment]
In display settings there is a video calibration. But from memory that only scales.

Maybe you could ask on KodiNerds. Someone might be able to create an overlay bar with adjustable position and size. One that blurs the image below it. Might be nice to have :-)

**Comment by Taijian** [comment]
> > Yes, tried Maven85's now, but failed. I can login and browse the DAZN content, but I cannot play any streams. Kodi logs a 403 error, when it tries to communicate with the license server.
> > Gonna do some more testing on the weekend I suppose.
> 
> Updated my setup to Nexus today and now the DAZN addon is working fine. I streamed some test content from last season, looks good. So I should be set for the upcoming games :)

Just out of curiosity: How did you get this to work? On my setup (CoreElec 20.1 on an Odroid N2+) with the DAZN addon from the KodiNerds Repo I cannot actually log in. It just tells me that my subscription to DAZN has expiered and to renew it.  :-(

**Comment by AleXSR700** [comment]
I just get told "Restart your DAZN today and experience.... Cancel online."

**Comment by Taijian** [comment]
Yeah, kinda like that. I should add that I am able to view NFL content just fine via Firefox and dazn.com.

**Comment by AleXSR700** [comment]
Fyi, the DAZN addon does not support the GP yet. But the dev will check it out soon :)

**Comment by jbarry786** [comment]
Is DAZN available in all of Europe? So anywhere in Europe (and UK), users have to sign up for Dazn?

**Comment by AleXSR700** [comment]
Not just Europe. DAZN is a British company but they have taken GPI for all regions, not just Europe.
Probably the only remaining NFL direct country will be the USA.Maybe even they are switched?

**Comment by jm-duke** [comment]
> Just out of curiosity: How did you get this to work?
I have kinda the same setup. I use the latest OSMC with Kodi 20.1 and Maven85's DAZN add-on from Kodinerds.

It probably works on my end, because for the moment I also have a standard DAZN subscription. I assume the add-on needs to add some extra logic to account for users with only the GP subscription.

**Comment by jm-duke** [comment]
> Not just Europe. DAZN is a British company but they have taken GPI for all regions, not just Europe. Probably the only remaining NFL direct country will be the USA.Maybe even they are switched?
No, in the US they still push their own NFL+ service.

**Comment by sieversMartin** [comment]
"Every NFL game during the 2023 regular season and playoffs — including the Super Bowl — is available worldwide on DAZN, excluding the United States and China."

"NFL GPI will be available through the DAZN app either as a standalone subscription or an add-on to an existing DAZN package to customers worldwide**, excluding the United States and China."

(https://www.dazn.com/en-US/news/american-football/how-much-is-nfl-game-pass-in-my-country/1nmnpcsga7nr41r2o7hfekzko6)

**Comment by jbarry786** [comment]
If you can come up with already existing Kodi settings or a new trick for these things:

- move "screen down" (hiding the bottom bar) or...
- crop bottom bar out

I'll also have to set some shortcuts, so we jump ahead 30 seconds, 3 minutes to skip game breaks and and commercials.  I also would like to manipulate the Kodi settings so we never see the length of the game at any point.

If a brighter mind already has these things done, please do share now or towards the start of the season.

**Comment by AleXSR700** [comment]
Not sure if the DAZN addon will show or hide the game length, but even in the NFL addon you were able to see the game length when you e.g. paused or called the UI.

Skipping is easy. Just set the steps in the settings. My default one click is 30 sec and double is 3 min.

No new info on cropping/shifting from my side. Best to check out the different repos.

**Comment by AleXSR700** [comment]
Any chance we can simply use the DAZN link in this addon so we can keep the clean look?
The DAZN app works now but it is of course for all users. So the pure GP experience is not a nice:)

**Comment by jm-duke** [comment]
Yeah, I was kinda thinking the same. I really do prefer the neat interface of this add-on to the simple list style of the DAZN add-on.

Changing the back-end of the GP add-on from the current streaming provider to DAZN is most likely an awful lot of work. So I thought about forking the DAZN add-on and kinda creating a GP special edition, which introduces this add-on's interface to the GP part of the DAZN add-on.

I'm not really convinced it is worth the effort though. I'd need to do a lot of reading on how the interface logic works in Kodi and I also don't know, how the 2024 season is going to look like. From what I gather from the notifications e-mails, the special offer for old GP users is only valid for the 2023 season, so who knows what happens next year...

**Comment by AleXSR700** [comment]
Which special offer? Seems like everybody (except the previous limited users) is going to pay normal, full price of 171.99 €.
If it is too much work, then so be it. Maybe the official DAZN app will actually be good enough to use and KODI will not be needed. But somehow I doubt any combination will be as slick as this addon was.

**Comment by jm-duke** [comment]
Yeah, the 171.99 is the special offer, which, as far as I understood, is valid for the 2023 season. I think they'll use the year to fully integrate the Gamepass offerings into the DAZN standard subscription, so they can charge 19.99 or 29.99 per month next year...

**Comment by AleXSR700** [comment]
Not sure if they would be allowed to. I would assume that the contract types are already agreed with the NFL
 So unless they agreed to remove the standalone gamepass , the gamepass should remain available standalone.

**Comment by jm-duke** [comment]
I really hope so and guess we'll see next year :)
