### ISSUE TITLE
Missing Option to resume where you left off

### ISSUE THREAD

**Issue by Jesia** [pigskin/kodi-gamepass#83]
First i want to thank you all for the great improvments you've done. Keep up !

But i noticed that the feature is gone where you could resume the game/show where you stoped the last time. I know that it's a small thing but i used it quite often .

So i'm wondering if you left it out on purpose?

Thanks

**Comment by Alexqw** [comment]
Krypton added this. I wonder if it'd help in the situation: http://forum.kodi.tv/showthread.php?tid=250862&pid=2211120#pid2211120

**Comment by kaileu** [comment]
As far as i understood its only a Skinning change what you mentioned but didn't help us while playing videos. I think that this is something that also have to be implemented in Inputstream.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
