### ISSUE TITLE
Bundle Font

### ISSUE THREAD

**Issue by aqw** [pigskin/kodi-gamepass#85]
XBMC doesn't have support for this yet, but the devs seem open to it. Once this addon makes it to the main repo, then we can talk with the devs about getting this feature supported.

The problem is that we inherit the font from the active skin in XBMC, and many of those fonts don't play nicely with our interface.

For now, we will continue targeting Confluence's font (as it is the default skin).

**Comment by Alexqw** [comment]
If anyone is interested, there's a conversation over in the Kodi forums about font issues for skinned addons.

http://forum.kodi.tv/showthread.php?tid=214140

**Comment by BaumSchorle** [comment]
I am currently working on a solution for this, as soon as I have something to test I will let you know!

**Comment by Alexqw** [comment]
@BaumSchorle /Awesome/. Did they finally provide a way for addon devs to solve this?!

**Comment by BaumSchorle** [comment]
@Alexqw No, there is still no solution for this, as far as I know.

However I found a way for a decent workaround. I stumbled over this library: https://github.com/mazkolain/xbmc-skinutils
The developer is a smart gui, we provide a font file and a font.xml which is dynamically added to the active skin and then the skin is reloaded. After leaving our addon, the skin is set back to it's original state.

What I like about it: 
* It is actually working. I have it already running on my system and tested it with 3 or 4 different skins and it looks nice everywhere.

What I don't like about it:
* we dynamically edit the font.xml of the skin
* if you are running on Confluence, the library copies the skin from the Kodi installation folder to the userdata folder and you need to restart Kodi to activate the Confluence Skin from the userdata folder.

**Comment by Alexqw** [comment]
@BaumSchorle I agree with your downsides. It's a very heavy-handed approach to a problem that should be solved in Kodi proper.

However, I agree with your statement that "It's actually working." It solves the problem, and it solves it now. I'm reassured that he's been developing and maintaining this solution for 4 years now. Though I am concerned that it seems there's not much of a community around the effort (1 contributor, no issues or PRs, no forks). It makes me wonder how broadly it has been tested.

That being said, as long as it is minimally invasive to our code and can be reverted easily (in case this chokes badly on the odd skins people use), then I'm all for it. As we should continue to bitch to the kodi devs that this really needs to be solved by them.

Thanks for looking into this. :-)

---Alex

**Comment by BaumSchorle** [comment]
This libraries are used in the popular Addon Spotimc and I think it is pretty well tested. I haven't come across any problem until now, it just works like a charm.

There is only one thing missing for a "complete skinned addon": We need to design our own select dialogs for selection of bitrate and full/condensed games.

**Comment by Alexqw** [comment]
Good to know it's well tested then. :-)

Are there problems with the default dialogs? I havn't noticed any problems.

**Comment by BaumSchorle** [comment]
It depends on the skin, I am using eminence and the selction dialogs are not looking any good. The OK-Dialogs are not the problem, at least not in eminence.

**Comment by BaumSchorle** [comment]
@Alexqw I created a pull request, maybe you want to test it with your skin!?

**Comment by Alexqw** [comment]
This is closed for now, but I am looking forward to Kodi doing this properly.

---Alex

**Comment by Alexqw** [comment]
Reopening, because of issue #184 
The skinutils patch lives on in the font-hack branch. Extra points and love for anyone who can convince upstream to complete this feature. Even better if you have the skills to complete the work yourself. :-)

https://github.com/xbmc/xbmc/pull/4743

---Alex

**Comment by Alexqw** [comment]
So... crazy idea, and I'm not sure (as in I doubt) that it's possible with Kodi's current feature-set, but there's no bad ideas in brainstorming... or something... right?

What if the addon were more of a scraper, that (assuming a valid subscription) could scrape the GamePass servers and setup the resources with proper auth and enter them into Kodi's library. That way all of the display issues become the responsibility of the skin (again). We wouldn't have font problems, the resume feature would work, favorites would work, etc.

The concern is, I don't know/think that Kodi has a media type of "Sports Game" or if it can even add streams as resources in the library. The scraping would have to be done frequently-ish to update info, and we'd have to work closely with at least one skin to act as a reference implementation for important features (game start-time, etc). And I don't know where Red-Zone or NFL Network would go in the library.

Perhaps all a little pie-in-the-sky...

Thoughts?

---Alex

**Comment by Ghoschdi** [comment]
@Alexqw I have very limited knowledge (still), but what you describe sounds a bit like the taken approach of the AMAZON VOD addon developed by Sandman. You provide your Amazon details and it fetches the information from the Instant Video servers but serves the Movies/Series via the standard Kodi 17. (video section) skin. The addon comes in two flavors: One of local database and one provided via Amazon. Github here: https://github.com/Sandmann79/xbmc

**Comment by Alexqw** [comment]
@Ghoschdi Sorry, your post slipped by me. I took a closer look at that amazon addon, and it seems he ships the actual db file, rather than an advanced form of scraper. :-/

I'm not a fan of that approach in general, but also it wouldn't work for us in practicality, as we'd have to have a way to push high frequency updates to the db (in the most extreme case, every few minutes on Sundays).

Thanks for keeping an eye out though. :-)

---Alex

**Comment by Ghoschdi** [comment]
@Alexqw No problems.  So he got rid of the challenge you describ, at least from what I have seen and how it works on my shield now. 

From my very quick glance at the code he seems to pull the info from the remote server, prepares it in a way that Kodi understands it and can display it in the normal video menu. For this reason he seems to use a DB file. In the newer VOD one (version 0.27) he got rid of the local DB and pulls info directly from amazon (to compose a new temporary db). The related new plugin is located in this github tree: https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test

This approach makes sense to me as you need to pass a lot of information you want to put into different categories. Wouldn't this also help to solve the request about having a team view?
Anyhow i still do not understand how Kodi builds the Video menu and how you can pass multiple elements like GP needs to do.

**Comment by aqw** [comment]
@Ghoschdi FYI, I changed my username today to 'aqw'. Just to reduce confusion. ;-)

If he's actually doing what you're saying, then that is very interesting indeed. It would also require skin support, but then that could be a general, in-Kodi solution to all type of sports. That's... very interesting. I need to talk with a Kodi dev and get their input.

---Alex

**Comment by aqw** [comment]
The Kodi PR (kinda) has new life: xbmc/xbmc#11136

Hope springs eternal.

---Alex

**Comment by aqw** [comment]
I wonder if this changed anything for us: xbmc/xbmc#11379

**Comment by jm-duke** [comment]
Doing some clean-up and this enhancement request is really old, so I'm closing it.
