### ISSUE TITLE
Create Team View

### ISSUE THREAD

**Issue by aqw** [pigskin/kodi-gamepass#89]
The flash interface has a way to view all games for a team in a season, rather than all games for a week in a season.

Getting the information is trivial. It's the exact same as get_weeks_games(), just don't post the "week" and instead post the "team".

The real work here is to make the GUI intuitive for users of both the team and week view.

**Comment by Alexqw** [comment]
Another option is we could copy/follow the convention that most skins have, where they have a hidden "view" menu off to the left. So when you press left (off the side of the screen), the settings pane comes out and you can change the view to a Team view.

Thoughts?

---Alex

**Comment by Alexqw** [comment]
@eriksoderblom @BaumSchorle Any thoughts on this one? My skinning skills are a bit limited to work on this. But I think it'd be really cool to have.

---Alex

**Comment by kaileu** [comment]
I would add in the week view the "week" Teams on first place.
if it is selected them it Shows all available games from the prefered Team selected in the settings.
![team](https://user-images.githubusercontent.com/4194147/27518123-aeaff3f6-59d8-11e7-8302-bffefde2bcc0.PNG)
![team-selected](https://user-images.githubusercontent.com/4194147/27518125-b5c67944-59d8-11e7-81c2-ed5b0ac2f632.PNG)
![team-selected-upcoming](https://user-images.githubusercontent.com/4194147/27518126-b5f39758-59d8-11e7-9cf5-eddb0a2b104b.PNG)

**Comment by aqw** [comment]
@kaileu Hmmm... in my opinion, we need a way to toggle between "weeks view" (for lack of a better name) and "teams view". The "weeks view" is the current interface, and the "teams view" lists every team on the left, and selecting that team will show its schedule on the right (much like what you have). Then, in settings, we can have a "default team" settings, and we'll pre-select that team when in the "teams view".

I'm not quite sure where this toggle should be for flipping between the two modes.

Thoughts?

---Alex

**Comment by kaileu** [comment]
This solution could be implemented without a new GUI.
And if you deselect the Teams View the Team Button isn't shown.

For the new Gui i have no Idea where the Buttons should be (i am not good in GUIs)
From the API standpoint we could make a page which Shows all Teams and you can select the Team Picture but this would be more GUI work.

**Comment by aqw** [comment]
@kaileu If we can insert a toggle/slider/some-obvious-button where you have "Teams" in the left column, that should be enough. When "Teams" view, we just list the teams instead of weeks. That probably involves the least amount of GUI work.

It's been awhile since I looked at Kodi's GUI stuff. I know they keep improving it. Perhaps we can use (or copy) some existing widget rather than having to design our own.

---Alex

**Comment by kaileu** [comment]
The Problem with a Radio button could be the Navigation with a remote.
So if you are at a Computer there is no Problem but if you didn't have a mouse it could be difficult.
I implemented it so that in default if you click on Teams there popup a list of all available Teams.

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
